- include: ../../../facts.yml

- name: Override src path
  set_fact:
      src_prefix: /vagrant
  when: is_dev_install

- name: Docker options
  set_fact: 
      docker_options: --insecure-registry dockerhub-proxy.cloudlinux.com:5000 --registry-mirror=https://dockerhub-proxy.cloudlinux.com:5000
  when: is_nebula

- name: Assign key
  authorized_key: user=root key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"

- name: Ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed

- name: Enable SELinux
  selinux: policy=targeted state=enforcing

- name: Set enforce for SELinux
  command: setenforce 1

- name: Add node to master
  shell: python "{{ src_prefix }}/manage.py" add_node --hostname {{ ansible_hostname }} --do-deploy {{ add_testing_repo }} --docker-options="{{ docker_options|default('')}}"
  delegate_facts: True
  delegate_to: "{{ groups['master'][0] }}"
  tags:
    - deploy

- set_fact: _hostname={{ hostvars[item].ansible_hostname }}
  with_items: "{{ groups['node'] }}"
  register: _hostnames

- set_fact: hostnames="{{ _hostnames.results|map(attribute='ansible_facts._hostname')|list|join(',')}}"

- name: Wait for nodes
  run_once: true
  shell: python "{{ src_prefix }}/manage.py" wait-for-nodes --nodes "{{ hostnames }}" --timeout 600
  delegate_facts: True
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: False
