- include: ../../../facts.yml

- name: Override src path
  set_fact:
      src_prefix: /vagrant
  when: is_dev_install

- name: Docker options
  set_fact:
      docker_options: --insecure-registry dockerhub-proxy.cloudlinux.com:5000 --registry-mirror=https://dockerhub-proxy.cloudlinux.com:5000
  when: is_nebula

- name: Assign key
  authorized_key: user=root key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"

- name: Ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed

- name: Enable SELinux
  selinux: policy=targeted state=enforcing

- name: Set enforce for SELinux
  command: setenforce 1

- include: deploy.yml
