- name: Assign key
  authorized_key: user=root key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"

- name: ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed

- name: Enable SELinux
  selinux: policy=targeted state=enforcing

- name: Set enforce for SELinux
  command: setenforce 1

- name: Add node to master
  shell: python /vagrant/manage.py add_node --hostname {{ ansible_hostname }} --kube-type 1 --do-deploy
  delegate_facts: True
  delegate_to: "{{ groups['master'][0] }}"
