#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#


# Please set valid IPs/credentials/data for you infrastructure. Otherwise
# many things will not work (incl. deploy, unittests, integration tests etc.)

- include: ../../../facts.yml

- set_fact:
    wait_node_timeout: 1200 # FIXME: Get from environment
  tags:
      - non_aws

- name: Docker options
  set_fact:
      docker_options: --insecure-registry=192.168.115.165:5001 --registry-mirror=http://192.168.115.165:5001
  when: is_nebula
  tags:
    - non_aws

- name: Assign key
  authorized_key: user={{ ansible_user }} key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"
  tags:
    - non_aws

- name: Ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed
  tags:
    - non_aws

- name: Enable SELinux
  selinux: policy=targeted state=enforcing
  tags:
    - non_aws

- name: Set enforce for SELinux
  command: setenforce 1
  tags:
    - non_aws

- include: zfs.yml
  when: use_zfs
  tags:
    - non_aws

- include: deploy.yml
  tags:
    - node_deploy
