- include: ../../../facts.yml

- name: Docker options
  set_fact:
      docker_options: --insecure-registry=192.168.115.165:5001 --registry-mirror=http://192.168.115.165:5001
  when: is_nebula

- name: Assign key
  authorized_key: user=root key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"

- name: Ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed

- name: Enable SELinux
  selinux: policy=targeted state=enforcing

- name: Set enforce for SELinux
  command: setenforce 1

- include: deploy.yml
