- include: ../../../facts.yml

- set_fact:
    wait_node_timeout: 600
  tags:
      - non_aws


- name: Docker options
  set_fact:
      docker_options: --insecure-registry=192.168.115.165:5001 --registry-mirror=http://192.168.115.165:5001
  when: is_nebula
  tags:
    - non_aws

- name: Assign key
  authorized_key: user={{ ansible_user }} key="{{ lookup('file', '/tmp/kd_rsa.pub') }}"
  tags:
    - non_aws

- name: Ensure python-selinux is installed on all nodes.
  yum: name=libselinux-python state=installed
  tags:
    - non_aws

- name: Enable SELinux
  selinux: policy=targeted state=enforcing
  tags:
    - non_aws

- name: Set enforce for SELinux
  command: setenforce 1
  tags:
    - non_aws

- include: zfs.yml
  when: use_zfs
  tags:
    - non_aws

- include: deploy.yml
  tags:
    - node_deploy

- name: Restart master emperor when nodes are deployed.
  run_once: true
  service: name=emperor.uwsgi state=restarted
  delegate_facts: True
  delegate_to: "{{ groups['master'][0] }}"
  when: hostvars[groups['master'][0]].restart_emperor|changed
