version: '2'
services:
  appcloud:
    build:
      context: .
      dockerfile: Dockerfile.centos7-test
    links:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      TEST_DB_HOST: postgres
    volumes:
      - ./artifacts:/artifacts

  redis:
    image: redis:2

  postgres:
    environment:
      POSTGRES_DB: testkuberdock
      POSTGRES_USER: kuberdock
      POSTGRES_PASSWORD: kuberdock2go
    image: postgres:9.2
