---

- name: Setup common tasks
  hosts: all
  become: yes
  any_errors_fatal: true
  roles:
      - common

- name: Setup master
  hosts: master
  any_errors_fatal: true
  become: yes
  roles:
      - master

- name: Setup nodes
  hosts: node
  any_errors_fatal: true
  become: yes
  roles:
      - node

- name: Setup rhosts
  hosts: rhost
  any_errors_fatal: true
  become: yes
  roles:
      - rhost
      - { role: plesk, when: install_plesk }
      - { role: whmcs, when: install_whmcs }

- hosts: master
  tasks:
    - name: Wait for async tasks
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 30
      with_items:
          - "{{ pa_async_results }}"
      tags:
        - predefined_apps

    - set_fact: kd_url="{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}"
    - debug: msg="https://{{ kd_url }} [user:admin, password:admin]"
      run_once: true
