#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- name: Setup common tasks
  hosts: all
  become: yes
  any_errors_fatal: true
  roles:
      - common

- name: Setup master
  hosts: master
  any_errors_fatal: true
  become: yes
  roles:
      - master

- name: Setup nodes
  hosts: node
  any_errors_fatal: true
  become: yes
  roles:
      - node

- name: Setup rhosts
  hosts: rhost
  any_errors_fatal: true
  become: yes
  roles:
      - rhost
      - { role: plesk, when: install_plesk }
      - { role: whmcs, when: install_whmcs }

- hosts: master
  become: yes
  tasks:
    - name: Wait for async tasks
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 30
      with_items:
          - "{{ pa_async_results }}"
      tags:
        - predefined_apps

    - set_fact: kd_url="{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}"
    - debug: msg="https://{{ kd_url }} [user:admin, password:admin]"
      run_once: true
