---

- name: Setup common tasks
  hosts: all
  become: yes
  any_errors_fatal: true
  roles:
      - common

- name: Setup master
  hosts: master
  any_errors_fatal: true
  become: yes
  roles:
      - master

- name: Setup nodes
  hosts: node
  any_errors_fatal: true
  become: yes
  roles:
      - node

- hosts: master
  tasks:
    - set_fact: kd_url="{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}"
    - debug: msg="http://{{ kd_url }}:5000 [user:admin, password:admin]"
      run_once: true
      when: is_dev_install
    - debug: msg="https://{{ kd_url }} [user:admin, password:admin]"
      run_once: true
      when: not is_dev_install
