---

- name: Setup common tasks
  hosts: all
  become: yes
  roles:
      - common

- hosts: master
  become: yes
  roles:
      - master

- hosts: node
  become: yes
  roles:
      - node

  post_tasks:
      - set_fact: kd_url="{{ hostvars[groups['master'][0]].ansible_all_ipv4_addresses | last }}"
      - debug: msg="http://{{ kd_url }}:5000 [user:admin, password:admin]"
        when: is_dev_install
      - debug: msg="https://{{ kd_url }} [user:admin, password:admin]"
        when: not is_dev_install

