#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
- name: Patching a UI
  lineinfile:
      dest: "{{ master_kd_src_path }}/kubedock/frontend/templates/apps/index.html"
      regexp: "{{ item }}"
      state: absent
  with_items:
      - "^(.*)remove this line to uncomment$"
      - "^(.*)remove next line to uncomment (end of block)$"
      - "^([ ]+)#}$"
  tags:
    - ui_patch

- name: Patching a UI on host
  become: False
  lineinfile:
      dest: "{{ host_proj_root }}/kubedock/frontend/templates/apps/index.html"
      regexp: "{{ item }}"
      state: absent
  with_items:
      - "^(.*)remove this line to uncomment$"
      - "^(.*)remove next line to uncomment (end of block)$"
      - "^([ ]+)#}$"
  delegate_to: localhost
  tags:
    - ui_patch

- name: Hide modified UI file from git
  become: False
  command: git update-index --assume-unchanged "{{ host_proj_root }}/kubedock/frontend/templates/apps/index.html"
  delegate_to: localhost
  tags:
    - ui_patch




