- name: Install additional dev packages
  yum: name={{ item }} state=latest
  with_items:
      - rpm-build
      - nodejs
      - nodejs-less
      - nodejs-clean-css

- fail: msg="You have extra Kuberdock RPM package in a repo. Please remove it and restart from scratch."
  when: rpm_exist.matched == 1 and rpm_exist.files[0].path != "/vagrant/kuberdock.rpm"

- name: Building RPM from source
  command: bash /vagrant/dev-utils/build-rpm.sh
  environment:
    KD_GIT_REF: "{{ git_ref | default('') }}"

- name: Notice not to unpack deploy.sh
  set_fact:
      deploy_extracted: true

- name: Override src path
  set_fact:
      src_prefix: /vagrant
