---

- name: Disable stuff
  service: name=emperor.uwsgi state=stopped

- name: Create tmux session
  shell: tmux has-session -t '{{ tmux_session_name }}'  || tmux new-session -d -s '{{ tmux_session_name }}'
  tags:
      - tmux

- name: Up wsgi
  command: tmux new-window -t '{{ tmux_session_name }}' -n wsgi/celery \; send-keys "uwsgi --ini /etc/uwsgi/vassals/kuberdock.ini  --uid nginx --gid nginx --worker-reload-mercy 0 --python-autoreload 1 --chdir {{ master_kd_src_path }} --pythonpath {{ master_kd_src_path }}" C-m chdir="{{ master_kd_src_path }}"
  when: not no_wsgi
  tags:
      - tmux

- seboolean: name=httpd_can_network_connect state=yes persistent=yes
  notify:
    - restart nginx

- include: prices.yml

- name: Increase session lifetime
  lineinfile:
    dest: "{{ master_kd_src_path }}/kubedock/settings.py"
    regexp: ^SESSION_LIFETIME =
    line: "SESSION_LIFETIME = {{ 24*60*60 }}"
