---

- name: Disable stuff
  service: name=emperor.uwsgi state=stopped enabled=no

- name: Create tmux session runnign script
  template:
      src: templates/run_wsgi_in_tmux.sh.j2
      dest: "{{ ansible_env.HOME }}/run_wsgi_in_tmux.sh"
      mode: u+rwx
  tags:
      - tmux

- name: Up wsgi
  command: "bash {{ ansible_env.HOME }}/run_wsgi_in_tmux.sh"
  when: not no_wsgi
  tags:
      - tmux

- seboolean: name=httpd_can_network_connect state=yes persistent=yes
  notify:
    - restart nginx

- include: prices.yml

- name: Increase session lifetime
  lineinfile:
    dest: "{{ master_kd_src_path }}/kubedock/settings.py"
    regexp: ^SESSION_LIFETIME =
    line: "SESSION_LIFETIME = {{ 24*60*60 }}"
