---
- name: Calculate network
  set_fact:
    network: "{{ ansible_default_ipv4.network }}/{{ansible_default_ipv4.netmask}}"

- name: Create IP pool
  shell: python "{{ master_kd_src_path }}/manage.py" create-ip-pool -s "{{ network | ipaddr('net') }}" -i {{ public_ips }}
  tags:
    - ippool
