---
- name: Calculate network
  set_fact:
    network: "{{ ansible_default_ipv4.network }}/{{ansible_default_ipv4.netmask}}"

- name: Create IP pool
  shell: python "{{ src_prefix }}/manage.py" create-ip-pool -s "{{ network | ipaddr('net') }}" -i {{ public_ips }}
