#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
# Requirement for ansible's uri module
# The dependency on httplib2 was removed in Ansible 2.1
- name: Install additional packages
  yum: name=python-httplib2 state=latest
  tags:
   - kcli

- stat: path="{{ master_rpms_dir }}/kcli.rpm"
  register: kcli_rpm

- fail: msg="kcli.rpm was not found"
  when: not kcli_rpm.stat.exists
  tags:
   - kcli

- name: Install kcli
  yum: name="{{ master_rpms_dir }}/kcli.rpm" state=present
  tags:
   - kcli

- name: Get API tokens
  uri:
    url: "{{ token_gathering_url}}"
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    validate_certs: no
    force_basic_auth: yes
  register: tokens
  until: tokens.status == 200
  retries: 5
  delay: 30
  with_items:
    - {username: 'test_user', password: 'test_user'}
    - {username: 'alt_test_user', password: 'alt_test_user'}
  tags:
   - kcli

- name: Duplicate kcli configs for test users
  command: "cp /etc/kubecli.conf /etc/kubecli_{{ item.item.username }}.conf"
  with_items: "{{ tokens.results }}"
  tags:
   - kcli

- name: Write auth tokens to the kcli configs for each test user
  lineinfile:
    dest: "/etc/kubecli_{{ item.item.username }}.conf"
    line: "token = {{ item.json.token }}"
    state: present
  with_items: "{{ tokens.results }}"
  tags:
   - kcli

- name: Make test_user a default user for kcli
  command: cp /etc/kubecli_test_user.conf /etc/kubecli.conf
  tags:
   - kcli
