# Requirement for ansible's uri module
# The dependency on httplib2 was removed in Ansible 2.1
- name: Install additional packages
  yum: name=python-httplib2 state=latest
  tags:
    - kcli

- stat: path=/vagrant/kcli.rpm
  register: kcli_rpm

- fail: msg="kcli.rpm was not found"
  when: not kcli_rpm.stat.exists
  tags:
   - kcli

- name: Install KCLI
  yum: name=/vagrant/kcli.rpm state=present
  tags:
   - kcli

- name: Get token for test_user
  uri:
    url: "{{ token_gathering_url}}"
    user: test_user
    password: test_user
    validate_certs: no
    force_basic_auth: yes
  register: raw_token
  until: raw_token.status == 200
  retries: 5
  delay: 30
  tags:
    - kcli

- name: Write kcli auth (test_user only for now!)
  lineinfile:
      dest: "/etc/kubecli.conf"
      line: "token = {{ raw_token.json.token }}"
      state: present
  tags:
    - kcli
