# Requirement for ansible's uri module
# The dependency on httplib2 was removed in Ansible 2.1
- name: Install additional packages
  yum: name=python-httplib2 state=latest
  tags:
   - kcli

- stat: path=/vagrant/kcli.rpm
  register: kcli_rpm

- fail: msg="kcli.rpm was not found"
  when: not kcli_rpm.stat.exists
  tags:
   - kcli

- name: Install KCLI
  yum: name=/vagrant/kcli.rpm state=present
  tags:
   - kcli

- name: Get API tokens
  uri:
    url: "{{ token_gathering_url}}"
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    validate_certs: no
    force_basic_auth: yes
  register: tokens
  until: tokens.status == 200
  retries: 5
  delay: 30
  with_items:
    - {username: 'test_user', password: 'test_user'}
    - {username: 'alt_test_user', password: 'alt_test_user'}
  tags:
   - kcli

- name: Duplicate KCLI configs for test users
  command: "cp /etc/kubecli.conf /etc/kubecli_{{ item.item.username }}.conf"
  with_items: "{{ tokens.results }}"
  tags:
   - kcli

- name: Write auth tokens to the KCLI configs for each test user
  lineinfile:
    dest: "/etc/kubecli_{{ item.item.username }}.conf"
    line: "token = {{ item.json.token }}"
    state: present
  with_items: "{{ tokens.results }}"
  tags:
   - kcli

- name: Make test_user a default user for KCLI
  command: cp /etc/kubecli_test_user.conf /etc/kubecli.conf
  tags:
   - kcli
