- name: Install kcli
  yum: name="{{ kcli_rpm_url }}" state=present
  tags:
    - kcli

- name: Get token for test_user
  uri:
    url: "{{ token_gathering_url}}"
    user: test_user
    password: test_user
    validate_certs: no
    force_basic_auth: yes
  register: raw_token
  until: raw_token.status == 200
  retries: 5
  delay: 30
  tags:
    - kcli

- name: Write kcli auth (test_user only for now!)
  lineinfile:
      dest: "/etc/kubecli.conf"
      line: "token = {{ raw_token.json.token }}"
      state: present
  tags:
    - kcli
