- name: Copy license file
  copy: src={{ license_path }} dest={{ copy_license_to }}
  when: license_path != 'patch'
  tags:
      - license
      - patch

- name: Patching a licensing
  lineinfile:
      dest: "{{ master_kd_src_path }}/kubedock/kapi/licensing.py"
      line: "def is_valid(): return True"
      state: present
  when: license_path == 'patch'
  register: restart_emperor
  tags:
      - license
      - patch

- name: Patching a licensing on host
  become: false
  lineinfile:
      dest: "{{ host_proj_root }}/kubedock/kapi/licensing.py"
      line: "def is_valid(): return True"
      state: present
  when: license_path == 'patch'
  delegate_to: localhost
  tags:
      - license
      - patch
      - non_aws

- name: Hide modified license file from git
  become: False
  command: git update-index --assume-unchanged "{{ host_proj_root }}/kubedock/kapi/licensing.py"
  delegate_to: localhost
  when: license_path == 'patch'
  tags:
      - license
      - patch
      - non_aws

