- include: ../../../facts.yml

- debug: msg="Builds directory on host - {{ host_builds_path }}"
- debug: msg="Install type - {{ install_type }}"

- name: Inject shared SSH pub keys
  authorized_key: user={{ ansible_user }} key={{ item }}
  when: add_ssh_pub_keys
  with_items: "{{ lookup('file', ssh_pub_keys_path).splitlines() }}"

- name: Install epel-release
  yum: name=epel-release state=latest

- name: Install additional packages
  yum: name={{ item }} state=latest
  with_items:
      - git
      - tmux
      - haveged

- name: start haveged
  service: name=haveged state=started
  tags:
    - non_aws

- name: Create master RPMs directory
  file: path="{{ master_rpms_dir }}" state=directory

- include: dev_predeploy.yml
  static: no
  when: is_dev_install
  tags:
    - non_aws

- include: qa_predeploy.yml
  static: no
  when: is_qa_install

- include: release_predeploy.yml
  static: no
  when: is_release_install

- name: Running cleanup (deploy.sh --cleanup)
  shell: echo "yes" | bash deploy.sh --cleanup chdir="{{ master_rpms_dir }}" | while IFS= read -r line; do echo "$(date) $line"; done
  register: cleanup_result
  tags:
    - cleanup
    - non_aws

- set_fact:
    cleanup_log: "{{ cleanup_result.stdout.split('\n') }}"
  when: add_timestamps
  tags:
    - non_aws
    - cleanup

- debug: var=cleanup_log
  when: add_timestamps
  tags:
    - cleanup
    - non_aws

- include: ceph.yml
  when: use_ceph

- include: zfs.yml
  when: use_zfs
  tags:
    - non_aws

- include: deploy.yml
  tags:
    - non_aws

- name: Reset password
  shell: python "{{ master_kd_src_path }}/manage.py" reset-password --set "{{ admin_password }}"

- include: dev_postdeploy.yml
  when: is_dev_install

- include: qa_postdeploy.yml
  when: is_qa_install

- include: release_postdeploy.yml
  when: is_release_install

- include: license.yml
  when: license_path is defined and license_path

- include: billing.yml

- name: Fetching key
  fetch: src={{ pub_key }} dest=/tmp/kd_rsa.pub fail_on_missing=yes flat=yes

- include: ip_pool.yml
  tags:
    - ippool

- name: Get existing users
  become_user: postgres
  command: psql -d kuberdock -t -c "select username from users;"
  register: users_stdout

- name: Create users
  shell: python "{{ master_kd_src_path }}/manage.py" create-user -u {{ item }} -p {{ item }} -r User
  when: item not in "{{ users_stdout.stdout.split('\n') }}'"
  with_items:
      - test_user
      - alt_test_user

- name: Update users timezone
  become_user: postgres
  command: psql -d kuberdock -c "UPDATE users SET timezone='{{ timezone }}';"
  when:  not ((timezone | default("")) == "")
  tags:
    - timezone

- include: predefined_apps.yml
  tags:
    - predefined_apps

- include: kdctl.yml

- include: kcli.yml

