- include: detect_vm.yml

- name: Install additional packages
  yum: name={{ item }} state=latest
  with_items:
      - epel-release
      - git
      - tmux

- include: dev_predeploy.yml
  when: is_dev_install

- find: paths=/vagrant/ patterns="kuberdock*.rpm" 
  register: rpm_exist
  tags:
      - deploy

- fail: msg="There is not any kuberdock*.rpm files found."
  when: rpm_exist.matched <= 0

- name: Unpack deploy.sh
  command: bash /vagrant/dev-utils/unpack-rpm.sh
  when: deploy_extracted is not defined

- name: Cleanup
  shell: echo "yes" | bash /vagrant/deploy.sh --cleanup

- name: Deploy 
  shell: echo "{{ ansible_all_ipv4_addresses | last }}" | bash deploy.sh {{ add_testing_repo }} chdir=/vagrant
  when: rpm_exist.matched > 0 and not use_ceph
  tags:
      - deploy

- include: ceph.yml
  when: use_ceph

- name: Reset password
  shell: python "{{ src_prefix }}/manage.py" reset-password --set admin

- include: dev_postdeploy.yml
  when: is_dev_install

- include: license.yml
  when: license_path is defined and license_path

- include: billing.yml

- seboolean: name=httpd_can_network_connect state=yes persistent=yes
  notify:
    - restart nginx

- name: Fetching key
  fetch: src={{ pub_key }} dest=/tmp/kd_rsa.pub fail_on_missing=yes flat=yes

- include: ip_pool.yml

- name: Create users
  shell: python "{{ src_prefix }}/manage.py" create-user -u {{ item }} -p {{ item }} -r User
  with_items:
      - test_user
      - alt_test_user

- include: predefined_apps.yml

