- include: ../../../facts.yml

- debug: msg="Builds directory on host - {{ host_builds_path }}"
- debug: msg="Install type - {{ install_type }}"

- name: Inject shared SSH pub keys
  authorized_key: user=root key={{ item }}
  when: add_ssh_pub_keys
  with_items: "{{ lookup('file', ssh_pub_keys_path).splitlines() }}"

- name: Install epel-release
  yum: name=epel-release state=latest

- name: Install additional packages
  yum: name={{ item }} state=latest
  with_items:
      - git
      - tmux
      - haveged

- name: start haveged
  service: name=haveged state=started

- name: Create master RPMs directory
  file: path="{{ master_rpms_dir }}" state=directory

- include: dev_predeploy.yml
  when: is_dev_install

- include: qa_predeploy.yml
  when: is_qa_install

- include: release_predeploy.yml
  when: is_release_install

- name: Running cleanup (deploy.sh --cleanup)
  shell: echo "yes" | bash deploy.sh --cleanup chdir="{{ master_rpms_dir }}"
  tags:
      - cleanup

- include: ceph.yml
  when: use_ceph

- include: deploy.yml

- name: Reset password
  shell: python "{{ master_kd_src_path }}/manage.py" reset-password --set "{{ admin_password }}"

- include: dev_postdeploy.yml
  when: is_dev_install

- include: qa_postdeploy.yml
  when: is_qa_install

- include: release_postdeploy.yml
  when: is_release_install

- include: license.yml
  when: license_path is defined and license_path

- include: billing.yml

- name: Fetching key
  fetch: src={{ pub_key }} dest=/tmp/kd_rsa.pub fail_on_missing=yes flat=yes

- include: ip_pool.yml
  tags:
    - ippool

- name: Create users
  shell: python "{{ master_kd_src_path }}/manage.py" create-user -u {{ item }} -p {{ item }} -r User
  with_items:
      - test_user
      - alt_test_user

- name: Update users timezone
  become_user: postgres
  command: psql -d kuberdock -c "UPDATE users SET timezone='{{ timezone }}';"
  when:  not ((timezone | default("")) == "")
  tags:
    - timezone

- include: predefined_apps.yml
- include: kdctl.yml
- include: kcli.yml

