- include: ../../../facts.yml

- name: Install epel-release
  yum: name=epel-release state=latest

- name: Install additional packages
  yum: name={{ item }} state=latest
  with_items:
      - git
      - tmux
      - haveged

- name: start haveged
  service: name=haveged state=started

- include: dev_predeploy.yml
  when: is_dev_install

- include: qa_predeploy.yml
  when: is_qa_install

- include: release_predeploy.yml
  when: is_release_install


- name: Cleanup
  shell: echo "yes" | bash /vagrant/deploy.sh --cleanup
  tags:
      - cleanup

- include: ceph.yml
  when: use_ceph

- include: deploy.yml

- name: Reset password
  shell: python "{{ src_prefix }}/manage.py" reset-password --set "{{ admin_password }}"

- include: dev_postdeploy.yml
  when: is_dev_install

- include: qa_postdeploy.yml
  when: is_qa_install

- include: release_postdeploy.yml
  when: is_release_install

- include: license.yml
  when: license_path is defined and license_path

- include: billing.yml

- name: Fetching key
  fetch: src={{ pub_key }} dest=/tmp/kd_rsa.pub fail_on_missing=yes flat=yes

- include: ip_pool.yml

- name: Create users
  shell: python "{{ src_prefix }}/manage.py" create-user -u {{ item }} -p {{ item }} -r User
  with_items:
      - test_user
      - alt_test_user

- include: predefined_apps.yml
- include: kdctl.yml
- include: kcli.yml

