- include: ../../../facts.yml

- name: Install additional packages
  yum: name={{ item }} state=latest
  with_items:
      - epel-release
      - git
      - tmux

- include: dev_predeploy.yml
  when: is_dev_install

- find: paths=/vagrant/ patterns="kuberdock*.rpm"
  register: rpm_exist

- fail: msg="There is not any kuberdock*.rpm files found."
  when: rpm_exist.matched <= 0
  tags:
      - deploy

- name: Unpack deploy.sh
  command: bash /vagrant/dev-utils/unpack-rpm.sh
  when: deploy_extracted is not defined

- name: Cleanup
  shell: echo "yes" | bash /vagrant/deploy.sh --cleanup
  tags:
      - cleanup

- include: ceph.yml
  when: use_ceph

- name: Deploy 
  shell: echo "{{ ansible_default_ipv4.address }}" | KD_OWNER_EMAIL=vagrant@dummy.com bash deploy.sh {{ add_testing_repo }} {{ non_floating_ips_mode }} {{ ceph_params|default("") }} chdir=/vagrant
  when: rpm_exist.matched > 0
  tags:
      - deploy

- name: Reset password
  shell: python "{{ src_prefix }}/manage.py" reset-password --set admin

- include: dev_postdeploy.yml
  when: is_dev_install

- include: license.yml
  when: license_path is defined and license_path

- include: billing.yml

- name: Fetching key
  fetch: src={{ pub_key }} dest=/tmp/kd_rsa.pub fail_on_missing=yes flat=yes

- include: ip_pool.yml

- name: Create users
  shell: python "{{ src_prefix }}/manage.py" create-user -u {{ item }} -p {{ item }} -r User
  with_items:
      - test_user
      - alt_test_user

- include: predefined_apps.yml
- include: kcli.yml

