#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- name: Get predefined apps
  git: repo="{{ predefined_apps_repo }}"
       version="{{ predefined_apps_branch }}"
       dest="{{ predefined_apps_dest }}"

- name: Find all apps
  find: paths="{{ predefined_apps_dest }}" patterns=*.yaml
  register: predefined_apps

- name: Add predefined apps
  shell: for i in {{ predefined_apps_dest }}/*.yaml; do name=$(basename "$i"); python "{{ master_kd_src_path }}"/manage.py add-predefined-app --name "$name" -t "$i"; done
  async: 3600
  poll: 0
  register: pa_async_results
