#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- name: Get token
  uri:
    url: "{{ token_gathering_url }}"
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: token_raw
  until: token_raw.status == 200
  retries: 5
  delay: 30
  tags:
    - billing

- name: Set prices for IP and PD
  uri:
    url: "https://{{ ansible_hostname }}/api/pricing/packages/0/?token={{ token_raw.json.token }}"
    method: PUT
    body: "price_ip=0.59&price_pstorage=0.99"
    validate_certs: false
  tags:
    - billing

- name: Set prices for kubes
  uri:
    url: "https://{{ ansible_hostname }}/api/pricing/packages/0/kubes/{{ item.kube }}/?token={{ token_raw.json.token }}"
    method: PUT
    body: "kube_price={{ item.price }}"
    validate_certs: false
  with_items:
    - { kube: '0', price: '0.04' }
    - { kube: '1', price: '0.39' }
    - { kube: '2', price: '1.25' }
  tags:
    - billing

