---

- find: paths={{ master_rpms_dir }} patterns="{{ item }}*.rpm"
  register: _rpm_exist
  with_items: "{{ rpms_to_check }}"
  tags:
      - rpm_packages

- set_fact:
    result: "{{ result | default({}) | combine( {item.item: item}) }}"
  with_items: "{{ _rpm_exist.results }}"
  no_log: True

- fail: msg="There is not any {{ item }}*.rpm file is not found."
  when: (result.{{ item }}.matched <= 0)
  with_items: "{{ rpms_to_check }}"
  tags:
      - rpm_packages
      - deploy

- name: Copy get_rpm_deploy_script.sh script to master RPMs dir
  copy:
      src: "{{ host_proj_root }}/dev-utils/get_rpm_deploy_script.sh"
      dest: "{{ master_rpms_dir }}"

- name: Unpack deploy.sh
  command: "bash {{ master_rpms_dir }}/get_rpm_deploy_script.sh {{ master_rpms_dir }} {{ master_rpms_dir }}"
  tags:
    - non_aws
