---

- find: paths="{{ build_dir }}" patterns="{{ item }}*.rpm"
  become: False
  delegate_to: localhost
  register: _rpms
  with_items: "{{ rpms_to_check }}"

- set_fact:
    rpms_list: "{{ rpms_list | default([]) | union(item.files) }}"
  with_items: "{{ _rpms.results }}"
  no_log: True

- name: Copy rpm packages
  copy: src={{ item.path }} dest=/vagrant
  with_items: "{{ rpms_list }}"

- include: process_rpm.yml
