#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- name: Get master
  set_fact:
      master_ip: "{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}"
  tags:
    - billing

- name: Get token
  uri:
    url: "https://{{ master_ip }}/api/auth/token"
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: token_raw
  until: token_raw.status == 200
  retries: 5
  delay: 30
  tags:
    - billing

- name: Set whmcs billing
  uri:
    url: "https://{{ master_ip }}/api/settings/sysapi/{{item.id}}/?token={{ token_raw.json.token }}"
    method: PUT
    body: ' {"id":{{ item.id }},"name":"{{ item.name }}","setting_group":"billing","value":"{{ item.value }}"}'
    body_format: json
    validate_certs: false
  with_items:
      - {id: 1, name: "billing_type", value: "WHMCS"}
      - {id: 2, name: "billing_url", value: "http://{{ whmcs_domain_name }}"}
      - {id: 3, name: "billing_username", value: "admin"}
      - {id: 4, name: "billing_password", value: "{{ whmcs_pass}}"}
  tags:
    - billing
