#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- name: Create file to activate plugin
  copy:
    src: files/activate_plugin.php
    dest: /home/whmcs/public_html/kdactivate.php
  tags:
    - whmcs_plugin

- name: Run this file
  command: php /home/whmcs/public_html/kdactivate.php
  tags:
    - whmcs_plugin

- name: Get KuberDock plugin version
  shell: cat "{{ kd_php_file }}" | grep version | cut -d"'" -f4
  register: kd_plugin_version
  tags:
    - whmcs_plugin

- name: Assure whmcs, that addon is activated
  command: mysql --database whmcs_db -e "{{ item }}"
  with_items:
    - INSERT INTO tbladdonmodules VALUES ('KuberDock', 'version', '{{  kd_plugin_version.stdout }}'), ('KuberDock', 'access', 1);
    - INSERT INTO tblconfiguration(setting, value) VALUES('ActiveAddonModules', 'KuberDock') ON DUPLICATE KEY UPDATE value='KuberDock';
    - INSERT INTO tblconfiguration(setting, value) VALUES('AddonModulesPerms', '{{ kd_addon_module_permissions }}') ON DUPLICATE KEY UPDATE value='{{ kd_addon_module_permissions }}';
    - INSERT INTO `tblpaymentgateways` VALUES ('mailin','name','Mail In Payment',1),('mailin','type','Invoices',0),('mailin','visible','on',0),('mailin','instructions','Bank Name:\r\nPayee Name:\r\nSort Code:\r\nAccount Number:',0),('mailin','convertto','',0);

  tags:
    - whmcs_plugin
