#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- find: paths={{ host_builds_path }} patterns="{{ item }}*.rpm"
  become: False
  delegate_to: localhost
  register: "_rpm_exist"
  with_items: "{{ rpms_to_check }}"

- set_fact:
    result: "{{ result | default({}) | combine( {item.item: item}) }}"
  with_items: "{{ _rpm_exist.results }}"
  no_log: True

- name: Check existing packages
  fail: msg="You have extra {{ item }} RPM package in a repo, it is only allowed to have '{{ item }}.rpm'. Please remove an extra RPM and restart from scratch."
  when: "result.{{ item }}.matched == 1 and (result.{{ item }}.files[0].path|basename) != '{{ item }}.rpm'"
  with_items: "{{ rpms_to_check }}"
