- include: ../../../facts.yml

- name: RPM proxy configure
  include: rpm_proxy.yml
  when: is_nebula

- name: upgrade all packages
  yum: name=* state=latest

- name: Fix default interface
  shell: route add -net 8.8.8.8 netmask 255.255.255.255 {{ ansible_interfaces | last }}
  when : ansible_default_ipv4.address=="10.0.2.15"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups.all }}"

- name: User dotfiles
  include: dotfiles.yml
  when: dotfiles is defined and dotfiles

- name: User hooks
  include: hook.yml
  when: hook is defined and hook
