#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- include: check_rpms.yml
  when: not is_release_install

# Needed for integration tests. Once CI images are updated, this can be
# removed.
- name: Ensure netcat is installed
  yum: name=nc state=installed

- include: ../../../facts.yml

- name: Update global environment variables
  lineinfile:
      dest: "/etc/environment"
      line: "SENTRY_ENABLE=n"
      state: present

- name: RPM proxy configure
  include: rpm_proxy.yml
  when: is_nebula

- include: ceph.yml

- include: vbox_patch.yml
  when : ansible_default_ipv4.address=="10.0.2.15"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn or hostvars[item].ansible_hostname }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups.all }}"

- name: User dotfiles
  include: dotfiles.yml
  static: no
  when: dotfiles is defined and dotfiles and is_dev_install
  tags:
    - dotfiles

- name: User hooks
  include: hook.yml
  when: hook is defined and hook and is_dev_install

- include: timezone.yml
