---

- include: check_rpms.yml
  when: not is_release_install

- name: Clean repositry cache
  command: yum clean all

- include: ../../../facts.yml

- name: Update global environment variables
  lineinfile:
      dest: "/etc/environment"
      line: "SENTRY_ENABLE=n"
      state: present

- name: RPM proxy configure
  include: rpm_proxy.yml
  when: is_nebula

- include: ceph.yml

- include: vbox_patch.yml
  when : ansible_default_ipv4.address=="10.0.2.15"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups.all }}"

- name: User dotfiles
  include: dotfiles.yml
  when: dotfiles is defined and dotfiles and is_dev_install

- name: User hooks
  include: hook.yml
  when: hook is defined and hook and is_dev_install
