---

- find: paths=/vagrant/ patterns="kuberdock*.rpm" 
  register: rpm_exist

- name: Check existing packages
  fail: msg="Too many kuberdock*.rpm packages found in a repo. Please remove everything except what you want to deploy and restart from scratch."
  when: rpm_exist.matched > 1

- name: Check existing dev packages
  fail: msg="You have extra KuberDock RPM package in a repo, for Dev install is is only allowed to have 'kuberdock.rpm'. Please remove an extra RPM and restart from scratch."
  when: is_dev_install and rpm_exist.matched == 1 and rpm_exist.files[0].path != "/vagrant/kuberdock.rpm"

- include: ../../../facts.yml

- name: Update global environment variables
  lineinfile:
      dest: "/etc/environment"
      line: "SENTRY_ENABLE=n"
      state: present

- name: RPM proxy configure
  include: rpm_proxy.yml
  when: is_nebula

- name: upgrade all packages
  yum: name=* state=latest

- include: vbox_patch.yml
  when : ansible_default_ipv4.address=="10.0.2.15"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups.all }}"

- name: User dotfiles
  include: dotfiles.yml
  when: dotfiles is defined and dotfiles

- name: User hooks
  include: hook.yml
  when: hook is defined and hook
