---

- name: Get network zone
  shell: cat /tmp/one_env | grep ETH0_NETWORK
  register: zn
  changed_when: False

- set_fact: proxy="{{ rpm_proxies[zn.stdout] | default(None) }}"

- name: Setting rpm proxy
  lineinfile:
      dest: "/etc/yum.conf"
      line: "proxy={{ proxy }}" 
      state: present
  when: proxy is defined and proxy
