---

- name: Get timezone from host
  run_once: true
  become: False
  delegate_to: localhost
  shell: readlink /etc/localtime | cut -d/ -f5,6
  when: timezone is not defined
  register: timezone_raw
  tags:
    - timezone

- set_fact:
    timezone: "{{ timezone_raw.stdout }}"
  when: timezone is not defined
  run_once: true
  tags:
    - timezone

- debug: msg="No timezone detected. Set KD_TIMEZONE or check your /etc/localtime symlink."
  run_once: true
  when: not timezone
  tags:
    - timezone

- name: Remove origin timezone
  file: path=/etc/localtime state=absent
  when: (timezone | default("")) != ""
  tags:
    - timezone

- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
  when: (timezone | default("")) != ""
  tags:
    - timezone
