tmux_session_name: kd_tmux_session
pub_key: /var/lib/nginx/.ssh/id_rsa.pub
copy_license_to: '/var/opt/kuberdock/.license'
master_rpms_dir: /tmp/master_rpms
predefined_apps_repo: https://github.com/cloudlinux/kuberdock_predefined_apps.git
predefined_apps_branch: 1.5.0-beta
predefined_apps_dest: /tmp/kuberdock_predefined_apps
token_gathering_url: https://localhost/api/auth/token

ceph_config_dest: "/tmp/ceph.conf"
ceph_user_keyring_dest: "/tmp/ceph.keyring"


deploy_log_file: /var/log/kuberdock_master_deploy.log
deploy_log_file_dst: /tmp/kd_master_deploy.log

deploy_script_url: http://repo.cloudlinux.com/kuberdock/deploy.sh
emperor_needs_restart: false
